import { userGet } from "@/action/user-get";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header/header";
import { Toaster } from "@/components/ui/sonner";
import { UserContextProvider } from "@/context/user.context";
import { RootProvider } from "@/providers/root";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const user = await userGet();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}
      antialiased prose max-w-none min-h-dvh flex flex-col`}
      >
        <RootProvider>
          <UserContextProvider user={user}>
            <Header />
            <>{children}</>
            <Footer />
            <Toaster className="not-prose" />
            <aside>{modal}</aside>
          </UserContextProvider>
        </RootProvider>
      </body>
    </html>
  );
}
